---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checknodehealth-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cluster-health-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checknodehealth-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-health-monitor
    spec:
      serviceAccountName: checknodehealth-controller
      containers:
        - name: controller
          image: mcr.microsoft.com/aks/cluster-health-monitor/cluster-health-monitor:latest
          command: ["/controller"]
          args:
            - "--v=5"
          imagePullPolicy: IfNotPresent
          env:
            - name: CHECKER_POD_IMAGE
              value: "mcr.microsoft.com/aks/cluster-health-monitor/cluster-health-monitor:latest"
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
