---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checknodehealth-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checknodehealth-controller
subjects:
- kind: ServiceAccount
  name: checknodehealth-controller
  namespace: kube-system
