---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checknodehealth-controller
rules:
- apiGroups:
  - clusterhealthmonitor.azure.com
  resources:
  - checknodehealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterhealthmonitor.azure.com
  resources:
  - checknodehealths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - health.aks.io
  resources:
  - upgradenodeinprogresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - health.aks.io
  resources:
  - healthsignals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - health.aks.io
  resources:
  - healthsignals/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: checknodehealth-controller
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
