# File based on https://github.com/imjohnbo/ok-to-test/blob/master/.github/workflows/ok-to-test.yml
name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write

    # Only run for PRs, not issue comments
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: slash command dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          permission: write

      - name: Print parameters as JSON
        run: |
          echo "{
            \"owner\": \"${{ github.repository_owner }}\",
            \"repo\": \"${{ github.repository }}\",
            \"actor\": \"${{ github.actor }}\"
          }"

      - name: Check OAuth scopes for collaborator permission GraphQL query
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Sending GraphQL request and printing OAuth scopes headers..."
          gh api graphql \
            -f query='
              query CollaboratorPermission($owner: String!, $repo: String!, $collaborator: String) {
                repository(owner: $owner, name: $repo) {
                  collaborators(login: $collaborator) {
                    edges {
                      permission
                    }
                  }
                }
              }
            ' \
            -F owner='Azure' \
            -F repo='cluster-health-monitor' \
            -F collaborator='ThatJuanGuy' \
            --header 'Accept: application/vnd.github.v4+json' \
            --verbose \
            | grep -i "X-OAuth-Scopes\|X-Accepted-OAuth-Scopes"
